/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package indumaticsgestion.guis.comun;

import indumaticsgestion.guis.principal.VentanaPrincipal;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author Maxi
 */
public class VentanaContenido extends javax.swing.JPanel {
    
    public VentanaPrincipal base;
    public JPanel padre;
    /**
     * Creates new form VentanaContenido
     * @param base
     * @param padre
     */
    public VentanaContenido(VentanaPrincipal base, JPanel padre) {
        this.padre = padre;
        this.base = base;
        initComponents();
        
    }
    
    public void goBack(){
        this.setVisible(false);
        setPanel(padre);
    }
    
    /**
     *
     * @param contenido
     */
    public  void setPanel(JPanel contenido){
        contenido.setVisible(true);
        base.jpContenido.removeAll();
        base.jpContenido.setLayout(new BorderLayout());
        base.jpContenido.add(contenido);
        base.jpContenido.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
