package indumaticsgestion.guis.comun.localidad;

import com.db4o.ObjectSet;
import indumaticsgestion.data.comun.Localidad;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maxi
 */
public class LocalidadesLista extends javax.swing.JPanel {

    private final dlgSelLocalidad padre;
    private final ObjectSet<Localidad> data;
    private final ListSelectionModel lsm;

    /**
     *
     * @param padre
     * @param data
     */
    public LocalidadesLista(dlgSelLocalidad padre, ObjectSet<Localidad> data) {
        initComponents();
        this.padre = padre;
        this.data = data;
        cargarTabla();
        lsm = jtData.getSelectionModel();
        lsm.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    if (jtData.getSelectedRowCount() > 0) {
                        setLocalidad((Localidad) jtData.getValueAt(jtData.getSelectedRow(), 0));
                    }
                }
            }
        });
    }

    private void cargarTabla() {
        DefaultTableModel dtm = (DefaultTableModel) jtData.getModel();
        for (Localidad loc : data) {
            Object[] o = new Object[3];
            o[0] = loc;
            o[1] = loc.getProvincia();
            o[2] = loc.getPais();
            dtm.addRow(o);
        }
        jtData.setModel(dtm);
    }

    private void setLocalidad(Localidad loc) {
        this.padre.localidad = loc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtData = new javax.swing.JTable();

        setOpaque(false);

        jScrollPane1.setOpaque(false);

        jtData.setAutoCreateRowSorter(true);
        jtData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Localidad", "Provincia", "Pais"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtData.setColumnSelectionAllowed(true);
        jtData.setOpaque(false);
        jScrollPane1.setViewportView(jtData);
        jtData.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtData;
    // End of variables declaration//GEN-END:variables
}
