/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package indumaticsgestion.guis.ventas;

import indumaticsgestion.data.comun.Telefono;
import indumaticsgestion.data.ventas.Cliente;
import indumaticsgestion.guis.comun.dlgAMTelefono;
import indumaticsgestion.guis.comun.localidad.dlgSelLocalidad;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maxi
 */
public class ClientesAM extends javax.swing.JPanel {

    Cliente cliente = new Cliente();

    /**
     * Creates new form ClientesAM
     */
    public ClientesAM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtId = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTelefonos = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        btnTelefonoAdd = new javax.swing.JButton();
        btnTelefonoEdit = new javax.swing.JButton();
        btnTelefonoDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        btnSelLocalidad = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtLocalidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtProvincia = new javax.swing.JTextField();
        jtPais = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtCp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setOpaque(false);

        jToolBar1.setBackground(new java.awt.Color(102, 153, 255));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indumaticsgestion/recursos/iconos/btn_save_32x32.gif"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("indumaticsgestion/recursos/strings"); // NOI18N
        jButton1.setToolTipText(bundle.getString("save")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(false);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indumaticsgestion/recursos/iconos/btn_cancel_32x32.gif"))); // NOI18N
        jButton2.setToolTipText(bundle.getString("cancel")); // NOI18N
        jButton2.setBorder(null);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setOpaque(false);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jPanel1.setOpaque(false);

        jLabel1.setText(bundle.getString("ClienteId")); // NOI18N

        jtId.setEditable(false);

        jLabel2.setText(bundle.getString("ClientesNombre")); // NOI18N

        jLabel3.setText(bundle.getString("ClientesDireccion")); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("Telefonos"))); // NOI18N
        jPanel3.setOpaque(false);

        jtTelefonos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Tipo", "Contacto", "Comentarios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtTelefonos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtTelefonos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtTelefonos);
        jtTelefonos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtTelefonos.getColumnModel().getColumnCount() > 0) {
            jtTelefonos.getColumnModel().getColumn(0).setMinWidth(100);
        }

        jToolBar2.setFloatable(false);
        jToolBar2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar2.setRollover(true);
        jToolBar2.setOpaque(false);

        btnTelefonoAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indumaticsgestion/recursos/iconos/btn_add_24x24.gif"))); // NOI18N
        btnTelefonoAdd.setToolTipText(bundle.getString("add")); // NOI18N
        btnTelefonoAdd.setBorder(null);
        btnTelefonoAdd.setFocusable(false);
        btnTelefonoAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTelefonoAdd.setOpaque(false);
        btnTelefonoAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTelefonoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonoAddActionPerformed(evt);
            }
        });
        jToolBar2.add(btnTelefonoAdd);

        btnTelefonoEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indumaticsgestion/recursos/iconos/btn_edit_24x24.gif"))); // NOI18N
        btnTelefonoEdit.setToolTipText(bundle.getString("edit")); // NOI18N
        btnTelefonoEdit.setBorder(null);
        btnTelefonoEdit.setFocusable(false);
        btnTelefonoEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTelefonoEdit.setOpaque(false);
        btnTelefonoEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTelefonoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonoEditActionPerformed(evt);
            }
        });
        jToolBar2.add(btnTelefonoEdit);

        btnTelefonoDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indumaticsgestion/recursos/iconos/btn_delete_24x24.gif"))); // NOI18N
        btnTelefonoDelete.setText(bundle.getString("delete")); // NOI18N
        btnTelefonoDelete.setToolTipText(bundle.getString("delete")); // NOI18N
        btnTelefonoDelete.setBorder(null);
        btnTelefonoDelete.setFocusable(false);
        btnTelefonoDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTelefonoDelete.setOpaque(false);
        btnTelefonoDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTelefonoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonoDeleteActionPerformed(evt);
            }
        });
        jToolBar2.add(btnTelefonoDelete);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("localidad"))); // NOI18N
        jPanel4.setOpaque(false);

        jToolBar3.setFloatable(false);
        jToolBar3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar3.setRollover(true);
        jToolBar3.setOpaque(false);

        btnSelLocalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/indumaticsgestion/recursos/iconos/options_24x24.gif"))); // NOI18N
        btnSelLocalidad.setToolTipText(bundle.getString("options")); // NOI18N
        btnSelLocalidad.setBorder(null);
        btnSelLocalidad.setFocusable(false);
        btnSelLocalidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSelLocalidad.setOpaque(false);
        btnSelLocalidad.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSelLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelLocalidadActionPerformed(evt);
            }
        });
        jToolBar3.add(btnSelLocalidad);

        jLabel5.setText(bundle.getString("localidad")); // NOI18N

        jtLocalidad.setEditable(false);
        jtLocalidad.setToolTipText("");

        jLabel6.setText(bundle.getString("provincia")); // NOI18N

        jtProvincia.setEditable(false);
        jtProvincia.setToolTipText("");

        jtPais.setEditable(false);
        jtPais.setToolTipText("");

        jLabel7.setText(bundle.getString("pais")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtLocalidad)
                    .addComponent(jtProvincia)
                    .addComponent(jtPais))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText(bundle.getString("cp")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtDireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(168, 168, 168)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jtCp, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("ClienteGeneral"), jPanel1); // NOI18N

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(bundle.getString("fiscal"), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelefonoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonoAddActionPerformed
        dlgAMTelefono dlg = new dlgAMTelefono(null, true, null);
        dlg.setVisible(true);
        if (dlg.returnStatus == dlgAMTelefono.RET_OK) {
            cliente.addTelefono(dlg.getTelefono());
            setTablaTelefonos();
        }
    }//GEN-LAST:event_btnTelefonoAddActionPerformed

    private void btnTelefonoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonoEditActionPerformed
        if (jtTelefonos.getSelectedRowCount() > 0) {
            dlgAMTelefono dlg = new dlgAMTelefono(null, true, (Telefono) jtTelefonos.getValueAt(jtTelefonos.getSelectedRow(), 0));
            dlg.setVisible(true);
            if (dlg.returnStatus == dlgAMTelefono.RET_OK) {
                cliente.updateTelefono(dlg.getTelefono());
                setTablaTelefonos();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Telefono!");
        }
    }//GEN-LAST:event_btnTelefonoEditActionPerformed

    private void btnTelefonoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonoDeleteActionPerformed
        if (jtTelefonos.getSelectedRowCount() > 0) {
            Telefono tel = (Telefono) jtTelefonos.getValueAt(jtTelefonos.getSelectedRow(), 0);
            String msg = "Esta seguro que desea borrar el Telefono [" + tel + "]?";
            int respuesta = JOptionPane.showConfirmDialog(null, msg, "Borrar Telefono...", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                cliente.removeTelefono(tel);
                setTablaTelefonos();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Telefono!");
        }
    }//GEN-LAST:event_btnTelefonoDeleteActionPerformed

    private void btnSelLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelLocalidadActionPerformed
        dlgSelLocalidad loc = new dlgSelLocalidad(null, true, cliente.getLocalidad());
        loc.setVisible(true);
        if (loc.returnStatus == dlgSelLocalidad.RET_OK) {
            cliente.setLocalidad(loc.localidad);
            setData();
        }
    }//GEN-LAST:event_btnSelLocalidadActionPerformed

    private void setTablaTelefonos() {
        DefaultTableModel dtm = (DefaultTableModel) jtTelefonos.getModel();
        dtm.setRowCount(0);
        for (Telefono tel : cliente.getTelefonos()) {
            Object[] obj = new Object[4];
            obj[0] = tel;
            obj[1] = tel.getTipo();
            obj[2] = tel.getContacto();
            obj[3] = tel.getComentario();
            dtm.addRow(obj);
        }
        jtTelefonos.setModel(dtm);
    }

    private void getData() {

    }

    private void setData() {
        jtLocalidad.setText(cliente.getLocalidad().getLocalidad());
        jtProvincia.setText(cliente.getLocalidad().getProvincia());
        jtPais.setText(cliente.getLocalidad().getPais());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelLocalidad;
    private javax.swing.JButton btnTelefonoAdd;
    private javax.swing.JButton btnTelefonoDelete;
    private javax.swing.JButton btnTelefonoEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JTextField jtCp;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JTextField jtId;
    private javax.swing.JTextField jtLocalidad;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtPais;
    private javax.swing.JTextField jtProvincia;
    private javax.swing.JTable jtTelefonos;
    // End of variables declaration//GEN-END:variables
}
